"""Eazy SDK storage layer: transport-agnostic account/session persistence."""

from __future__ import annotations

from eazy_sdk.storage.entities import (
    Account,
    AccountEvent,
    AccountEventRecord,
    AccountEventType,
    AccountLink,
    AccountLinkRecord,
    AccountRecord,
    AccountStatus,
    Credentials,
    Restriction,
    RestrictionRecord,
    Session,
    SessionData,
    SessionRecord,
    Verification,
    VerificationRecord,
)
from eazy_sdk.storage.exceptions import (
    AccountLeasedError,
    AccountNotFoundError,
    AccountUnavailableError,
    DuplicateAccountError,
    SessionNotFoundError,
    StorageBackendError,
    StorageError,
)
from eazy_sdk.storage.memory import (
    InMemoryAccountRepository,
    InMemoryEventStore,
    InMemoryLinkRepository,
    InMemoryRestrictionRepository,
    InMemorySessionRepository,
    InMemoryVerificationRepository,
    MemoryStorage,
)
from eazy_sdk.storage.middleware import EventRecordingMiddleware, LoggingMiddleware
from eazy_sdk.storage.repository import (
    AccountRepository,
    EventStore,
    LinkRepository,
    Repository,
    RestrictionRepository,
    SessionRepository,
    VerificationRepository,
)
from eazy_sdk.storage.services import (
    AccountLinks,
    AccountPool,
    Accounts,
    AccountWorkspace,
    History,
    Restrictions,
    Sessions,
    Verifications,
)
from eazy_sdk.storage.session_bridge import RepositorySessionStore, SessionCodec
from eazy_sdk.storage.storage import (
    BaseStorageMiddleware,
    Storage,
    StorageMiddleware,
    StorageOp,
)

__all__ = [
    "Account",
    "AccountEvent",
    "AccountEventRecord",
    "AccountEventType",
    "AccountLeasedError",
    "AccountLink",
    "AccountLinkRecord",
    "AccountLinks",
    "AccountNotFoundError",
    "AccountPool",
    "AccountRecord",
    "AccountRepository",
    "AccountStatus",
    "AccountUnavailableError",
    "AccountWorkspace",
    "Accounts",
    "BaseStorageMiddleware",
    "Credentials",
    "DuplicateAccountError",
    "EventRecordingMiddleware",
    "EventStore",
    "History",
    "InMemoryAccountRepository",
    "InMemoryEventStore",
    "InMemoryLinkRepository",
    "InMemoryRestrictionRepository",
    "InMemorySessionRepository",
    "InMemoryVerificationRepository",
    "LinkRepository",
    "LoggingMiddleware",
    "MemoryStorage",
    "Repository",
    "RepositorySessionStore",
    "Restriction",
    "RestrictionRecord",
    "RestrictionRepository",
    "Restrictions",
    "Session",
    "SessionCodec",
    "SessionData",
    "SessionNotFoundError",
    "SessionRecord",
    "SessionRepository",
    "Sessions",
    "Storage",
    "StorageBackendError",
    "StorageError",
    "StorageMiddleware",
    "StorageOp",
    "Verification",
    "VerificationRecord",
    "VerificationRepository",
    "Verifications",
]
